name: sauf_o_mat_display_app
description: "Sauf-O-Mat display app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.5
  window_manager: ^0.4.3
  syncfusion_flutter_charts: ^29.2.5
  flutter_svg: ^2.2.0
  http: ^1.4.0
  jose: ^0.3.4
  flutter_dotenv: ^5.2.1
  flutter_webrtc: ^0.14.2
  web_socket_channel: ^3.0.3
  google_fonts: ^6.3.0
  intl: ^0.20.2
  flutter_tilt: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/server.key
    - assets/billboard.png
    - assets/billboard_pink.png
    - assets/scroll.png
    - assets/parchment.png
    - assets/newspaper.png
    - assets/arrow_up.svg
    - assets/beer_foam.svg
    - assets/cowboy_chasing.gif
    - assets/placeholder_group.png
    - assets/placeholder_single.png
    - assets/placeholder_timetable.png
    - assets/timetable.png
    - assets/bottle_spin.gif
    - assets/kiss.gif
    - assets/rose_wreath.png
    - assets/prize_0.png
    - assets/prize_1.png
    - assets/prize_2.png
    - assets/bullet_hole_angled.png
    - assets/bullet_hole_angled_grey.png
    - assets/background.png
    - assets/flame.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
